
var countries = {
	"AF":{"countryNameJP":"アフガニスタン","countryNameEN":"Afghanistan","codeNum":"4","code3Char":"AFG","code2Char":"AF","place":"中東"},
	"AL":{"countryNameJP":"アルバニア","countryNameEN":"Albania","codeNum":"8","code3Char":"ALB","code2Char":"AL","place":"東ヨーロッパ"},
	"AQ":{"countryNameJP":"南極","countryNameEN":"Antarctica","codeNum":"10","code3Char":"ATA","code2Char":"AQ","place":"南極"},
	"DZ":{"countryNameJP":"アルジェリア","countryNameEN":"Algeria","codeNum":"12","code3Char":"DZA","code2Char":"DZ","place":"北アフリカ"},
	"AS":{"countryNameJP":"アメリカ領サモア","countryNameEN":"American Samoa","codeNum":"16","code3Char":"ASM","code2Char":"AS","place":"オセアニア"},
	"AD":{"countryNameJP":"アンドラ","countryNameEN":"Andorra","codeNum":"20","code3Char":"AND","code2Char":"AD","place":"西ヨーロッパ"},
	"AO":{"countryNameJP":"アンゴラ","countryNameEN":"Angola","codeNum":"24","code3Char":"AGO","code2Char":"AO","place":"南アフリカ"},
	"AG":{"countryNameJP":"アンティグア・バーブーダ","countryNameEN":"Antigua and Barbuda","codeNum":"28","code3Char":"ATG","code2Char":"AG","place":"中央アメリカ"},
	"AZ":{"countryNameJP":"アゼルバイジャン","countryNameEN":"Azerbaijan","codeNum":"31","code3Char":"AZE","code2Char":"AZ","place":"東ヨーロッパ"},
	"AR":{"countryNameJP":"アルゼンチン","countryNameEN":"Argentina","codeNum":"32","code3Char":"ARG","code2Char":"AR","place":"南アメリカ"},
	"AU":{"countryNameJP":"オーストラリア","countryNameEN":"Australia","codeNum":"36","code3Char":"AUS","code2Char":"AU","place":"オセアニア"},
	"AT":{"countryNameJP":"オーストリア","countryNameEN":"Austria","codeNum":"40","code3Char":"AUT","code2Char":"AT","place":"東ヨーロッパ"},
	"BS":{"countryNameJP":"バハマ","countryNameEN":"Bahamas","codeNum":"44","code3Char":"BHS","code2Char":"BS","place":"中央アメリカ"},
	"BH":{"countryNameJP":"バーレーン","countryNameEN":"Bahrain","codeNum":"48","code3Char":"BHR","code2Char":"BH","place":"中東"},
	"BD":{"countryNameJP":"バングラデシュ","countryNameEN":"Bangladesh","codeNum":"50","code3Char":"BGD","code2Char":"BD","place":"南アジア"},
	"AM":{"countryNameJP":"アルメニア","countryNameEN":"Armenia","codeNum":"51","code3Char":"ARM","code2Char":"AM","place":"東ヨーロッパ"},
	"BB":{"countryNameJP":"バルバドス","countryNameEN":"Barbados","codeNum":"52","code3Char":"BRB","code2Char":"BB","place":"中央アメリカ"},
	"BE":{"countryNameJP":"ベルギー","countryNameEN":"Belgium","codeNum":"56","code3Char":"BEL","code2Char":"BE","place":"西ヨーロッパ"},
	"BM":{"countryNameJP":"バミューダ諸島","countryNameEN":"Bermuda","codeNum":"60","code3Char":"BMU","code2Char":"BM","place":"中央アメリカ"},
	"BT":{"countryNameJP":"ブータン","countryNameEN":"Bhutan","codeNum":"64","code3Char":"BTN","code2Char":"BT","place":"南アジア"},
	"BO":{"countryNameJP":"ボリビア","countryNameEN":"Bolivia, Plurinational State of","codeNum":"68","code3Char":"BOL","code2Char":"BO","place":"南アメリカ"},
	"BA":{"countryNameJP":"ボスニア・ヘルツェゴビナ","countryNameEN":"Bosnia and Herzegovina","codeNum":"70","code3Char":"BIH","code2Char":"BA","place":"東ヨーロッパ"},
	"BW":{"countryNameJP":"ボツワナ","countryNameEN":"Botswana","codeNum":"72","code3Char":"BWA","code2Char":"BW","place":"南アフリカ"},
	"BV":{"countryNameJP":"ブーベ島","countryNameEN":"Bouvet Island","codeNum":"74","code3Char":"BVT","code2Char":"BV","place":"南極"},
	"BR":{"countryNameJP":"ブラジル","countryNameEN":"Brazil","codeNum":"76","code3Char":"BRA","code2Char":"BR","place":"南アメリカ"},
	"BZ":{"countryNameJP":"ベリーズ","countryNameEN":"Belize","codeNum":"84","code3Char":"BLZ","code2Char":"BZ","place":"中央アメリカ"},
	"IO":{"countryNameJP":"イギリス領インド洋地域","countryNameEN":"British Indian Ocean Territory","codeNum":"86","code3Char":"IOT","code2Char":"IO","place":"インド洋地域"},
	"SB":{"countryNameJP":"ソロモン諸島","countryNameEN":"Solomon Islands","codeNum":"90","code3Char":"SLB","code2Char":"SB","place":"オセアニア"},
	"VG":{"countryNameJP":"イギリス領ヴァージン諸島","countryNameEN":"Virgin Islands, British","codeNum":"92","code3Char":"VGB","code2Char":"VG","place":"中央アメリカ"},
	"BN":{"countryNameJP":"ブルネイ","countryNameEN":"Brunei Darussalam","codeNum":"96","code3Char":"BRN","code2Char":"BN","place":"東南アジア"},
	"BG":{"countryNameJP":"ブルガリア","countryNameEN":"Bulgaria","codeNum":"100","code3Char":"BGR","code2Char":"BG","place":"東ヨーロッパ"},
	"MM":{"countryNameJP":"ミャンマー","countryNameEN":"Myanmar","codeNum":"104","code3Char":"MMR","code2Char":"MM","place":"東南アジア"},
	"BI":{"countryNameJP":"ブルンジ","countryNameEN":"Burundi","codeNum":"108","code3Char":"BDI","code2Char":"BI","place":"中央アフリカ"},
	"BY":{"countryNameJP":"ベラルーシ","countryNameEN":"Belarus","codeNum":"112","code3Char":"BLR","code2Char":"BY","place":"東ヨーロッパ"},
	"KH":{"countryNameJP":"カンボジア","countryNameEN":"Cambodia","codeNum":"116","code3Char":"KHM","code2Char":"KH","place":"東南アジア"},
	"CM":{"countryNameJP":"カメルーン","countryNameEN":"Cameroon","codeNum":"120","code3Char":"CMR","code2Char":"CM","place":"中央アフリカ"},
	"CA":{"countryNameJP":"カナダ","countryNameEN":"Canada","codeNum":"124","code3Char":"CAN","code2Char":"CA","place":"北アメリカ"},
	"CV":{"countryNameJP":"カーボベルデ","countryNameEN":"Cape Verde","codeNum":"132","code3Char":"CPV","code2Char":"CV","place":"西アフリカ"},
	"KY":{"countryNameJP":"ケイマン諸島","countryNameEN":"Cayman Islands","codeNum":"136","code3Char":"CYM","code2Char":"KY","place":"中央アメリカ"},
	"CF":{"countryNameJP":"中央アフリカ","countryNameEN":"Central African Republic","codeNum":"140","code3Char":"CAF","code2Char":"CF","place":"中央アフリカ"},
	"LK":{"countryNameJP":"スリランカ","countryNameEN":"Sri Lanka","codeNum":"144","code3Char":"LKA","code2Char":"LK","place":"南アジア"},
	"TD":{"countryNameJP":"チャド","countryNameEN":"Chad","codeNum":"148","code3Char":"TCD","code2Char":"TD","place":"中央アフリカ"},
	"CL":{"countryNameJP":"チリ","countryNameEN":"Chile","codeNum":"152","code3Char":"CHL","code2Char":"CL","place":"南アメリカ"},
	"CN":{"countryNameJP":"中華人民共和国","countryNameEN":"China","codeNum":"156","code3Char":"CHN","code2Char":"CN","place":"東アジア"},
	"TW":{"countryNameJP":"台湾（台湾省/中華民国）","countryNameEN":"Taiwan, Province of China","codeNum":"158","code3Char":"TWN","code2Char":"TW","place":"東アジア"},
	"CX":{"countryNameJP":"クリスマス島","countryNameEN":"Christmas Island","codeNum":"162","code3Char":"CXR","code2Char":"CX","place":"オセアニア"},
	"CC":{"countryNameJP":"ココス諸島","countryNameEN":"Cocos (Keeling) Islands","codeNum":"166","code3Char":"CCK","code2Char":"CC","place":"インド洋地域"},
	"CO":{"countryNameJP":"コロンビア","countryNameEN":"Colombia","codeNum":"170","code3Char":"COL","code2Char":"CO","place":"南アメリカ"},
	"KM":{"countryNameJP":"コモロ","countryNameEN":"Comoros","codeNum":"174","code3Char":"COM","code2Char":"KM","place":"インド洋地域"},
	"YT":{"countryNameJP":"マヨット","countryNameEN":"Mayotte","codeNum":"175","code3Char":"MYT","code2Char":"YT","place":"インド洋地域"},
	"CG":{"countryNameJP":"コンゴ共和国","countryNameEN":"Congo","codeNum":"178","code3Char":"COG","code2Char":"CG","place":"中央アフリカ"},
	"CD":{"countryNameJP":"コンゴ民主共和国","countryNameEN":"Congo, the Democratic Republic of the","codeNum":"180","code3Char":"COD","code2Char":"CD","place":"中央アフリカ"},
	"CK":{"countryNameJP":"クック諸島","countryNameEN":"Cook Islands","codeNum":"184","code3Char":"COK","code2Char":"CK","place":"オセアニア"},
	"CR":{"countryNameJP":"コスタリカ","countryNameEN":"Costa Rica","codeNum":"188","code3Char":"CRI","code2Char":"CR","place":"中央アメリカ"},
	"HR":{"countryNameJP":"クロアチア","countryNameEN":"Croatia","codeNum":"191","code3Char":"HRV","code2Char":"HR","place":"東ヨーロッパ"},
	"CU":{"countryNameJP":"キューバ","countryNameEN":"Cuba","codeNum":"192","code3Char":"CUB","code2Char":"CU","place":"中央アメリカ"},
	"CY":{"countryNameJP":"キプロス","countryNameEN":"Cyprus","codeNum":"196","code3Char":"CYP","code2Char":"CY","place":"地中海地域"},
	"CZ":{"countryNameJP":"チェコ","countryNameEN":"Czech Republic","codeNum":"203","code3Char":"CZE","code2Char":"CZ","place":"東ヨーロッパ"},
	"BJ":{"countryNameJP":"ベナン","countryNameEN":"Benin","codeNum":"204","code3Char":"BEN","code2Char":"BJ","place":"西アフリカ"},
	"DK":{"countryNameJP":"デンマーク","countryNameEN":"Denmark","codeNum":"208","code3Char":"DNK","code2Char":"DK","place":"北ヨーロッパ"},
	"DM":{"countryNameJP":"ドミニカ国","countryNameEN":"Dominica","codeNum":"212","code3Char":"DMA","code2Char":"DM","place":"中央アメリカ"},
	"DO":{"countryNameJP":"ドミニカ共和国","countryNameEN":"Dominican Republic","codeNum":"214","code3Char":"DOM","code2Char":"DO","place":"中央アメリカ"},
	"EC":{"countryNameJP":"エクアドル","countryNameEN":"Ecuador","codeNum":"218","code3Char":"ECU","code2Char":"EC","place":"南アメリカ"},
	"SV":{"countryNameJP":"エルサルバドル","countryNameEN":"El Salvador","codeNum":"222","code3Char":"SLV","code2Char":"SV","place":"中央アメリカ"},
	"GQ":{"countryNameJP":"赤道ギニア","countryNameEN":"Equatorial Guinea","codeNum":"226","code3Char":"GNQ","code2Char":"GQ","place":"中央アフリカ"},
	"ET":{"countryNameJP":"エチオピア","countryNameEN":"Ethiopia","codeNum":"231","code3Char":"ETH","code2Char":"ET","place":"東アフリカ"},
	"ER":{"countryNameJP":"エリトリア","countryNameEN":"Eritrea","codeNum":"232","code3Char":"ERI","code2Char":"ER","place":"東アフリカ"},
	"EE":{"countryNameJP":"エストニア","countryNameEN":"Estonia","codeNum":"233","code3Char":"EST","code2Char":"EE","place":"東ヨーロッパ"},
	"FO":{"countryNameJP":"フェロー諸島","countryNameEN":"Faroe Islands","codeNum":"234","code3Char":"FRO","code2Char":"FO","place":"北ヨーロッパ"},
	"FK":{"countryNameJP":"フォークランド諸島","countryNameEN":"Falkland Islands (Malvinas)","codeNum":"238","code3Char":"FLK","code2Char":"FK","place":"南アメリカ"},
	"GS":{"countryNameJP":"サウスジョージア・サウスサンドウィッチ諸島","countryNameEN":"South Georgia and the South Sandwich Islands","codeNum":"239","code3Char":"SGS","code2Char":"GS","place":"南アメリカ"},
	"FJ":{"countryNameJP":"フィジー","countryNameEN":"Fiji","codeNum":"242","code3Char":"FJI","code2Char":"FJ","place":"オセアニア"},
	"FI":{"countryNameJP":"フィンランド","countryNameEN":"Finland","codeNum":"246","code3Char":"FIN","code2Char":"FI","place":"北ヨーロッパ"},
	"AX":{"countryNameJP":"オーランド諸島","countryNameEN":"Åland Islands","codeNum":"248","code3Char":"ALA","code2Char":"AX","place":"北ヨーロッパ"},
	"FR":{"countryNameJP":"フランス","countryNameEN":"France","codeNum":"250","code3Char":"FRA","code2Char":"FR","place":"西ヨーロッパ"},
	"GF":{"countryNameJP":"フランス領ギアナ","countryNameEN":"French Guiana","codeNum":"254","code3Char":"GUF","code2Char":"GF","place":"南アメリカ"},
	"PF":{"countryNameJP":"フランス領ポリネシア","countryNameEN":"French Polynesia","codeNum":"258","code3Char":"PYF","code2Char":"PF","place":"オセアニア"},
	"TF":{"countryNameJP":"フランス領南方・南極地域","countryNameEN":"French Southern Territories","codeNum":"260","code3Char":"ATF","code2Char":"TF","place":"インド洋地域"},
	"DJ":{"countryNameJP":"ジブチ","countryNameEN":"Djibouti","codeNum":"262","code3Char":"DJI","code2Char":"DJ","place":"東アフリカ"},
	"GA":{"countryNameJP":"ガボン","countryNameEN":"Gabon","codeNum":"266","code3Char":"GAB","code2Char":"GA","place":"中央アフリカ"},
	"GE":{"countryNameJP":"グルジア","countryNameEN":"Georgia","codeNum":"268","code3Char":"GEO","code2Char":"GE","place":"東ヨーロッパ"},
	"GM":{"countryNameJP":"ガンビア","countryNameEN":"Gambia","codeNum":"270","code3Char":"GMB","code2Char":"GM","place":"西アフリカ"},
	"PS":{"countryNameJP":"パレスチナ","countryNameEN":"Palestinian Territory, Occupied","codeNum":"275","code3Char":"PSE","code2Char":"PS","place":"中東"},
	"DE":{"countryNameJP":"ドイツ","countryNameEN":"Germany","codeNum":"276","code3Char":"DEU","code2Char":"DE","place":"西ヨーロッパ"},
	"GH":{"countryNameJP":"ガーナ","countryNameEN":"Ghana","codeNum":"288","code3Char":"GHA","code2Char":"GH","place":"西アフリカ"},
	"GI":{"countryNameJP":"ジブラルタル","countryNameEN":"Gibraltar","codeNum":"292","code3Char":"GIB","code2Char":"GI","place":"西ヨーロッパ"},
	"KI":{"countryNameJP":"キリバス","countryNameEN":"Kiribati","codeNum":"296","code3Char":"KIR","code2Char":"KI","place":"オセアニア"},
	"GR":{"countryNameJP":"ギリシャ","countryNameEN":"Greece","codeNum":"300","code3Char":"GRC","code2Char":"GR","place":"西ヨーロッパ"},
	"GL":{"countryNameJP":"グリーンランド","countryNameEN":"Greenland","codeNum":"304","code3Char":"GRL","code2Char":"GL","place":"北ヨーロッパ"},
	"GD":{"countryNameJP":"グレナダ","countryNameEN":"Grenada","codeNum":"308","code3Char":"GRD","code2Char":"GD","place":"中央アメリカ"},
	"GP":{"countryNameJP":"グアドループ","countryNameEN":"Guadeloupe","codeNum":"312","code3Char":"GLP","code2Char":"GP","place":"中央アメリカ"},
	"GU":{"countryNameJP":"グアム","countryNameEN":"Guam","codeNum":"316","code3Char":"GUM","code2Char":"GU","place":"オセアニア"},
	"GT":{"countryNameJP":"グアテマラ","countryNameEN":"Guatemala","codeNum":"320","code3Char":"GTM","code2Char":"GT","place":"中央アメリカ"},
	"GN":{"countryNameJP":"ギニア","countryNameEN":"Guinea","codeNum":"324","code3Char":"GIN","code2Char":"GN","place":"西アフリカ"},
	"GY":{"countryNameJP":"ガイアナ","countryNameEN":"Guyana","codeNum":"328","code3Char":"GUY","code2Char":"GY","place":"南アメリカ"},
	"HT":{"countryNameJP":"ハイチ","countryNameEN":"Haiti","codeNum":"332","code3Char":"HTI","code2Char":"HT","place":"中央アメリカ"},
	"HM":{"countryNameJP":"ハード島とマクドナルド諸島","countryNameEN":"Heard Island and McDonald Islands","codeNum":"334","code3Char":"HMD","code2Char":"HM","place":"インド洋地域"},
	"VA":{"countryNameJP":"バチカン","countryNameEN":"Holy See (Vatican City State)","codeNum":"336","code3Char":"VAT","code2Char":"VA","place":"西ヨーロッパ"},
	"HN":{"countryNameJP":"ホンジュラス","countryNameEN":"Honduras","codeNum":"340","code3Char":"HND","code2Char":"HN","place":"中央アメリカ"},
	"HK":{"countryNameJP":"香港","countryNameEN":"Hong Kong","codeNum":"344","code3Char":"HKG","code2Char":"HK","place":"東アジア"},
	"HU":{"countryNameJP":"ハンガリー","countryNameEN":"Hungary","codeNum":"348","code3Char":"HUN","code2Char":"HU","place":"東ヨーロッパ"},
	"IS":{"countryNameJP":"アイスランド","countryNameEN":"Iceland","codeNum":"352","code3Char":"ISL","code2Char":"IS","place":"北ヨーロッパ"},
	"IN":{"countryNameJP":"インド","countryNameEN":"India","codeNum":"356","code3Char":"IND","code2Char":"IN","place":"南アジア"},
	"ID":{"countryNameJP":"インドネシア","countryNameEN":"Indonesia","codeNum":"360","code3Char":"IDN","code2Char":"ID","place":"東南アジア"},
	"IR":{"countryNameJP":"イラン","countryNameEN":"Iran, Islamic Republic of","codeNum":"364","code3Char":"IRN","code2Char":"IR","place":"中東"},
	"IQ":{"countryNameJP":"イラク","countryNameEN":"Iraq","codeNum":"368","code3Char":"IRQ","code2Char":"IQ","place":"中東"},
	"IE":{"countryNameJP":"アイルランド","countryNameEN":"Ireland","codeNum":"372","code3Char":"IRL","code2Char":"IE","place":"西ヨーロッパ"},
	"IL":{"countryNameJP":"イスラエル","countryNameEN":"Israel","codeNum":"376","code3Char":"ISR","code2Char":"IL","place":"中東"},
	"IT":{"countryNameJP":"イタリア","countryNameEN":"Italy","codeNum":"380","code3Char":"ITA","code2Char":"IT","place":"西ヨーロッパ"},
	"CI":{"countryNameJP":"コートジボワール","countryNameEN":"Côte d'Ivoire","codeNum":"384","code3Char":"CIV","code2Char":"CI","place":"西アフリカ"},
	"JM":{"countryNameJP":"ジャマイカ","countryNameEN":"Jamaica","codeNum":"388","code3Char":"JAM","code2Char":"JM","place":"中央アメリカ"},
	"JP":{"countryNameJP":"日本","countryNameEN":"Japan","codeNum":"392","code3Char":"JPN","code2Char":"JP","place":"東アジア"},
	"KZ":{"countryNameJP":"カザフスタン","countryNameEN":"Kazakhstan","codeNum":"398","code3Char":"KAZ","code2Char":"KZ","place":"中央アジア"},
	"JO":{"countryNameJP":"ヨルダン","countryNameEN":"Jordan","codeNum":"400","code3Char":"JOR","code2Char":"JO","place":"中東"},
	"KE":{"countryNameJP":"ケニア","countryNameEN":"Kenya","codeNum":"404","code3Char":"KEN","code2Char":"KE","place":"東アフリカ"},
	"KP":{"countryNameJP":"朝鮮民主主義人民共和国","countryNameEN":"Korea, Democratic People's Republic of","codeNum":"408","code3Char":"PRK","code2Char":"KP","place":"東アジア"},
	"KR":{"countryNameJP":"大韓民国","countryNameEN":"Korea, Republic of","codeNum":"410","code3Char":"KOR","code2Char":"KR","place":"東アジア"},
	"KW":{"countryNameJP":"クウェート","countryNameEN":"Kuwait","codeNum":"414","code3Char":"KWT","code2Char":"KW","place":"中東"},
	"KG":{"countryNameJP":"キルギス","countryNameEN":"Kyrgyzstan","codeNum":"417","code3Char":"KGZ","code2Char":"KG","place":"中央アジア"},
	"LA":{"countryNameJP":"ラオス","countryNameEN":"Lao People's Democratic Republic","codeNum":"418","code3Char":"LAO","code2Char":"LA","place":"東南アジア"},
	"LB":{"countryNameJP":"レバノン","countryNameEN":"Lebanon","codeNum":"422","code3Char":"LBN","code2Char":"LB","place":"中東"},
	"LS":{"countryNameJP":"レソト","countryNameEN":"Lesotho","codeNum":"426","code3Char":"LSO","code2Char":"LS","place":"南アフリカ"},
	"LV":{"countryNameJP":"ラトビア","countryNameEN":"Latvia","codeNum":"428","code3Char":"LVA","code2Char":"LV","place":"東ヨーロッパ"},
	"LR":{"countryNameJP":"リベリア","countryNameEN":"Liberia","codeNum":"430","code3Char":"LBR","code2Char":"LR","place":"西アフリカ"},
	"LY":{"countryNameJP":"リビア","countryNameEN":"Libyan Arab Jamahiriya","codeNum":"434","code3Char":"LBY","code2Char":"LY","place":"北アフリカ"},
	"LI":{"countryNameJP":"リヒテンシュタイン","countryNameEN":"Liechtenstein","codeNum":"438","code3Char":"LIE","code2Char":"LI","place":"西ヨーロッパ"},
	"LT":{"countryNameJP":"リトアニア","countryNameEN":"Lithuania","codeNum":"440","code3Char":"LTU","code2Char":"LT","place":"東ヨーロッパ"},
	"LU":{"countryNameJP":"ルクセンブルク","countryNameEN":"Luxembourg","codeNum":"442","code3Char":"LUX","code2Char":"LU","place":"西ヨーロッパ"},
	"MO":{"countryNameJP":"マカオ","countryNameEN":"Macao","codeNum":"446","code3Char":"MAC","code2Char":"MO","place":"東アジア"},
	"MG":{"countryNameJP":"マダガスカル","countryNameEN":"Madagascar","codeNum":"450","code3Char":"MDG","code2Char":"MG","place":"インド洋地域"},
	"MW":{"countryNameJP":"マラウイ","countryNameEN":"Malawi","codeNum":"454","code3Char":"MWI","code2Char":"MW","place":"南アフリカ"},
	"MY":{"countryNameJP":"マレーシア","countryNameEN":"Malaysia","codeNum":"458","code3Char":"MYS","code2Char":"MY","place":"東南アジア"},
	"MV":{"countryNameJP":"モルディブ","countryNameEN":"Maldives","codeNum":"462","code3Char":"MDV","code2Char":"MV","place":"インド洋地域"},
	"ML":{"countryNameJP":"マリ","countryNameEN":"Mali","codeNum":"466","code3Char":"MLI","code2Char":"ML","place":"西アフリカ"},
	"MT":{"countryNameJP":"マルタ","countryNameEN":"Malta","codeNum":"470","code3Char":"MLT","code2Char":"MT","place":"地中海地域"},
	"MQ":{"countryNameJP":"マルティニーク","countryNameEN":"Martinique","codeNum":"474","code3Char":"MTQ","code2Char":"MQ","place":"中央アメリカ"},
	"MR":{"countryNameJP":"モーリタニア","countryNameEN":"Mauritania","codeNum":"478","code3Char":"MRT","code2Char":"MR","place":"西アフリカ"},
	"MU":{"countryNameJP":"モーリシャス","countryNameEN":"Mauritius","codeNum":"480","code3Char":"MUS","code2Char":"MU","place":"南アフリカ"},
	"MX":{"countryNameJP":"メキシコ","countryNameEN":"Mexico","codeNum":"484","code3Char":"MEX","code2Char":"MX","place":"中央アメリカ"},
	"MC":{"countryNameJP":"モナコ","countryNameEN":"Monaco","codeNum":"492","code3Char":"MCO","code2Char":"MC","place":"西ヨーロッパ"},
	"MN":{"countryNameJP":"モンゴル","countryNameEN":"Mongolia","codeNum":"496","code3Char":"MNG","code2Char":"MN","place":"東アジア"},
	"MD":{"countryNameJP":"モルドバ","countryNameEN":"Moldova, Republic of","codeNum":"498","code3Char":"MDA","code2Char":"MD","place":"東ヨーロッパ"},
	"ME":{"countryNameJP":"モンテネグロ","countryNameEN":"Montenegro","codeNum":"499","code3Char":"MNE","code2Char":"ME","place":"東ヨーロッパ"},
	"MS":{"countryNameJP":"モントセラト","countryNameEN":"Montserrat","codeNum":"500","code3Char":"MSR","code2Char":"MS","place":"中央アメリカ"},
	"MA":{"countryNameJP":"モロッコ","countryNameEN":"Morocco","codeNum":"504","code3Char":"MAR","code2Char":"MA","place":"北アフリカ"},
	"MZ":{"countryNameJP":"モザンビーク","countryNameEN":"Mozambique","codeNum":"508","code3Char":"MOZ","code2Char":"MZ","place":"南アフリカ"},
	"OM":{"countryNameJP":"オマーン","countryNameEN":"Oman","codeNum":"512","code3Char":"OMN","code2Char":"OM","place":"中東"},
	"NA":{"countryNameJP":"ナミビア","countryNameEN":"Namibia","codeNum":"516","code3Char":"NAM","code2Char":"NA","place":"南アフリカ"},
	"NR":{"countryNameJP":"ナウル","countryNameEN":"Nauru","codeNum":"520","code3Char":"NRU","code2Char":"NR","place":"オセアニア"},
	"NP":{"countryNameJP":"ネパール","countryNameEN":"Nepal","codeNum":"524","code3Char":"NPL","code2Char":"NP","place":"南アジア"},
	"NL":{"countryNameJP":"オランダ","countryNameEN":"Netherlands","codeNum":"528","code3Char":"NLD","code2Char":"NL","place":"西ヨーロッパ"},
	"AN":{"countryNameJP":"オランダ領アンティル","countryNameEN":"Netherlands Antilles","codeNum":"530","code3Char":"ANT","code2Char":"AN","place":"中央アメリカ"},
	"AW":{"countryNameJP":"アルバ","countryNameEN":"Aruba","codeNum":"533","code3Char":"ABW","code2Char":"AW","place":"中央アメリカ"},
	"NC":{"countryNameJP":"ニューカレドニア","countryNameEN":"New Caledonia","codeNum":"540","code3Char":"NCL","code2Char":"NC","place":"オセアニア"},
	"VU":{"countryNameJP":"バヌアツ","countryNameEN":"Vanuatu","codeNum":"548","code3Char":"VUT","code2Char":"VU","place":"オセアニア"},
	"NZ":{"countryNameJP":"ニュージーランド","countryNameEN":"New Zealand","codeNum":"554","code3Char":"NZL","code2Char":"NZ","place":"オセアニア"},
	"NI":{"countryNameJP":"ニカラグア","countryNameEN":"Nicaragua","codeNum":"558","code3Char":"NIC","code2Char":"NI","place":"中央アメリカ"},
	"NE":{"countryNameJP":"ニジェール","countryNameEN":"Niger","codeNum":"562","code3Char":"NER","code2Char":"NE","place":"中央アフリカ"},
	"NG":{"countryNameJP":"ナイジェリア","countryNameEN":"Nigeria","codeNum":"566","code3Char":"NGA","code2Char":"NG","place":"中央アフリカ"},
	"NU":{"countryNameJP":"ニウエ","countryNameEN":"Niue","codeNum":"570","code3Char":"NIU","code2Char":"NU","place":"オセアニア"},
	"NF":{"countryNameJP":"ノーフォーク島","countryNameEN":"Norfolk Island","codeNum":"574","code3Char":"NFK","code2Char":"NF","place":"オセアニア"},
	"NO":{"countryNameJP":"ノルウェー","countryNameEN":"Norway","codeNum":"578","code3Char":"NOR","code2Char":"NO","place":"北ヨーロッパ"},
	"MP":{"countryNameJP":"北マリアナ諸島","countryNameEN":"Northern Mariana Islands","codeNum":"580","code3Char":"MNP","code2Char":"MP","place":"オセアニア"},
	"UM":{"countryNameJP":"合衆国領有小離島","countryNameEN":"United States Minor Outlying Islands","codeNum":"581","code3Char":"UMI","code2Char":"UM","place":"オセアニア"},
	"FM":{"countryNameJP":"ミクロネシア連邦","countryNameEN":"Micronesia, Federated States of","codeNum":"583","code3Char":"FSM","code2Char":"FM","place":"オセアニア"},
	"MH":{"countryNameJP":"マーシャル諸島","countryNameEN":"Marshall Islands","codeNum":"584","code3Char":"MHL","code2Char":"MH","place":"オセアニア"},
	"PW":{"countryNameJP":"パラオ","countryNameEN":"Palau","codeNum":"585","code3Char":"PLW","code2Char":"PW","place":"オセアニア"},
	"PK":{"countryNameJP":"パキスタン","countryNameEN":"Pakistan","codeNum":"586","code3Char":"PAK","code2Char":"PK","place":"南アジア"},
	"PA":{"countryNameJP":"パナマ","countryNameEN":"Panama","codeNum":"591","code3Char":"PAN","code2Char":"PA","place":"中央アメリカ"},
	"PG":{"countryNameJP":"パプアニューギニア","countryNameEN":"Papua New Guinea","codeNum":"598","code3Char":"PNG","code2Char":"PG","place":"オセアニア"},
	"PY":{"countryNameJP":"パラグアイ","countryNameEN":"Paraguay","codeNum":"600","code3Char":"PRY","code2Char":"PY","place":"南アメリカ"},
	"PE":{"countryNameJP":"ペルー","countryNameEN":"Peru","codeNum":"604","code3Char":"PER","code2Char":"PE","place":"南アメリカ"},
	"PH":{"countryNameJP":"フィリピン","countryNameEN":"Philippines","codeNum":"608","code3Char":"PHL","code2Char":"PH","place":"東南アジア"},
	"PN":{"countryNameJP":"ピトケアン","countryNameEN":"Pitcairn","codeNum":"612","code3Char":"PCN","code2Char":"PN","place":"オセアニア"},
	"PL":{"countryNameJP":"ポーランド","countryNameEN":"Poland","codeNum":"616","code3Char":"POL","code2Char":"PL","place":"東ヨーロッパ"},
	"PT":{"countryNameJP":"ポルトガル","countryNameEN":"Portugal","codeNum":"620","code3Char":"PRT","code2Char":"PT","place":"西ヨーロッパ"},
	"GW":{"countryNameJP":"ギニアビサウ","countryNameEN":"Guinea-Bissau","codeNum":"624","code3Char":"GNB","code2Char":"GW","place":"西アフリカ"},
	"TL":{"countryNameJP":"東ティモール","countryNameEN":"Timor-Leste","codeNum":"626","code3Char":"TLS","code2Char":"TL","place":"東南アジア"},
	"PR":{"countryNameJP":"プエルトリコ","countryNameEN":"Puerto Rico","codeNum":"630","code3Char":"PRI","code2Char":"PR","place":"中央アメリカ"},
	"QA":{"countryNameJP":"カタール","countryNameEN":"Qatar","codeNum":"634","code3Char":"QAT","code2Char":"QA","place":"中東"},
	"RE":{"countryNameJP":"レユニオン","countryNameEN":"Réunion","codeNum":"638","code3Char":"REU","code2Char":"RE","place":"インド洋地域"},
	"RO":{"countryNameJP":"ルーマニア","countryNameEN":"Romania","codeNum":"642","code3Char":"ROU","code2Char":"RO","place":"東ヨーロッパ"},
	"RU":{"countryNameJP":"ロシア","countryNameEN":"Russian Federation","codeNum":"643","code3Char":"RUS","code2Char":"RU","place":"ロシア"},
	"RW":{"countryNameJP":"ルワンダ","countryNameEN":"Rwanda","codeNum":"646","code3Char":"RWA","code2Char":"RW","place":"中央アフリカ"},
	"BL":{"countryNameJP":"サン・バルテルミー島","countryNameEN":"Saint Barthélemy","codeNum":"652","code3Char":"BLM","code2Char":"BL","place":"中央アメリカ"},
	"SH":{"countryNameJP":"セントヘレナ・アセンションおよびトリスタン・ダ・クーニャ","countryNameEN":"Saint Helena, Ascension and Tristan da Cunha","codeNum":"654","code3Char":"SHN","code2Char":"SH","place":"西アフリカ"},
	"KN":{"countryNameJP":"セントクリストファー・ネイビス","countryNameEN":"Saint Kitts and Nevis","codeNum":"659","code3Char":"KNA","code2Char":"KN","place":"中央アメリカ"},
	"AI":{"countryNameJP":"アンギラ","countryNameEN":"Anguilla","codeNum":"660","code3Char":"AIA","code2Char":"AI","place":"中央アメリカ"},
	"LC":{"countryNameJP":"セントルシア","countryNameEN":"Saint Lucia","codeNum":"662","code3Char":"LCA","code2Char":"LC","place":"中央アメリカ"},
	"MF":{"countryNameJP":"サン・マルタン島","countryNameEN":"Saint Martin (French part)","codeNum":"663","code3Char":"MAF","code2Char":"MF","place":"中央アメリカ"},
	"PM":{"countryNameJP":"サンピエール島・ミクロン島","countryNameEN":"Saint Pierre and Miquelon","codeNum":"666","code3Char":"SPM","code2Char":"PM","place":"北アメリカ"},
	"VC":{"countryNameJP":"セントビンセント・グレナディーン","countryNameEN":"Saint Vincent and the Grenadines","codeNum":"670","code3Char":"VCT","code2Char":"VC","place":"中央アメリカ"},
	"SM":{"countryNameJP":"サンマリノ","countryNameEN":"San Marino","codeNum":"674","code3Char":"SMR","code2Char":"SM","place":"西ヨーロッパ"},
	"ST":{"countryNameJP":"サントメ・プリンシペ","countryNameEN":"Sao Tome and Principe","codeNum":"678","code3Char":"STP","code2Char":"ST","place":"中央アフリカ"},
	"SA":{"countryNameJP":"サウジアラビア","countryNameEN":"Saudi Arabia","codeNum":"682","code3Char":"SAU","code2Char":"SA","place":"中東"},
	"SN":{"countryNameJP":"セネガル","countryNameEN":"Senegal","codeNum":"686","code3Char":"SEN","code2Char":"SN","place":"西アフリカ"},
	"RS":{"countryNameJP":"セルビア","countryNameEN":"Serbia","codeNum":"688","code3Char":"SRB","code2Char":"RS","place":"東ヨーロッパ"},
	"SC":{"countryNameJP":"セーシェル","countryNameEN":"Seychelles","codeNum":"690","code3Char":"SYC","code2Char":"SC","place":"インド洋地域"},
	"SL":{"countryNameJP":"シエラレオネ","countryNameEN":"Sierra Leone","codeNum":"694","code3Char":"SLE","code2Char":"SL","place":"西アフリカ"},
	"SG":{"countryNameJP":"シンガポール","countryNameEN":"Singapore","codeNum":"702","code3Char":"SGP","code2Char":"SG","place":"東南アジア"},
	"SK":{"countryNameJP":"スロバキア","countryNameEN":"Slovakia","codeNum":"703","code3Char":"SVK","code2Char":"SK","place":"東ヨーロッパ"},
	"VN":{"countryNameJP":"ベトナム","countryNameEN":"Viet Nam","codeNum":"704","code3Char":"VNM","code2Char":"VN","place":"東南アジア"},
	"SI":{"countryNameJP":"スロベニア","countryNameEN":"Slovenia","codeNum":"705","code3Char":"SVN","code2Char":"SI","place":"東ヨーロッパ"},
	"SO":{"countryNameJP":"ソマリア","countryNameEN":"Somalia","codeNum":"706","code3Char":"SOM","code2Char":"SO","place":"東アフリカ"},
	"ZA":{"countryNameJP":"南アフリカ","countryNameEN":"South Africa","codeNum":"710","code3Char":"ZAF","code2Char":"ZA","place":"南アフリカ"},
	"ZW":{"countryNameJP":"ジンバブエ","countryNameEN":"Zimbabwe","codeNum":"716","code3Char":"ZWE","code2Char":"ZW","place":"南アフリカ"},
	"ES":{"countryNameJP":"スペイン","countryNameEN":"Spain","codeNum":"724","code3Char":"ESP","code2Char":"ES","place":"西ヨーロッパ"},
	"EH":{"countryNameJP":"西サハラ","countryNameEN":"Western Sahara","codeNum":"732","code3Char":"ESH","code2Char":"EH","place":"西アフリカ"},
	"SD":{"countryNameJP":"スーダン","countryNameEN":"Sudan","codeNum":"736","code3Char":"SDN","code2Char":"SD","place":"東アフリカ"},
	"SR":{"countryNameJP":"スリナム","countryNameEN":"Suriname","codeNum":"740","code3Char":"SUR","code2Char":"SR","place":"南アメリカ"},
	"SJ":{"countryNameJP":"スヴァールバル諸島およびヤンマイエン島","countryNameEN":"Svalbard and Jan Mayen","codeNum":"744","code3Char":"SJM","code2Char":"SJ","place":"北ヨーロッパ"},
	"SZ":{"countryNameJP":"スワジランド","countryNameEN":"Swaziland","codeNum":"748","code3Char":"SWZ","code2Char":"SZ","place":"南アフリカ"},
	"SE":{"countryNameJP":"スウェーデン","countryNameEN":"Sweden","codeNum":"752","code3Char":"SWE","code2Char":"SE","place":"北ヨーロッパ"},
	"CH":{"countryNameJP":"スイス","countryNameEN":"Switzerland","codeNum":"756","code3Char":"CHE","code2Char":"CH","place":"西ヨーロッパ"},
	"SY":{"countryNameJP":"シリア","countryNameEN":"Syrian Arab Republic","codeNum":"760","code3Char":"SYR","code2Char":"SY","place":"中東"},
	"TJ":{"countryNameJP":"タジキスタン","countryNameEN":"Tajikistan","codeNum":"762","code3Char":"TJK","code2Char":"TJ","place":"中央アジア"},
	"TH":{"countryNameJP":"タイ","countryNameEN":"Thailand","codeNum":"764","code3Char":"THA","code2Char":"TH","place":"東南アジア"},
	"TG":{"countryNameJP":"トーゴ","countryNameEN":"Togo","codeNum":"768","code3Char":"TGO","code2Char":"TG","place":"西アフリカ"},
	"TK":{"countryNameJP":"トケラウ","countryNameEN":"Tokelau","codeNum":"772","code3Char":"TKL","code2Char":"TK","place":"オセアニア"},
	"TO":{"countryNameJP":"トンガ","countryNameEN":"Tonga","codeNum":"776","code3Char":"TON","code2Char":"TO","place":"オセアニア"},
	"TT":{"countryNameJP":"トリニダード・トバゴ","countryNameEN":"Trinidad and Tobago","codeNum":"780","code3Char":"TTO","code2Char":"TT","place":"中央アメリカ"},
	"AE":{"countryNameJP":"アラブ首長国連邦","countryNameEN":"United Arab Emirates","codeNum":"784","code3Char":"ARE","code2Char":"AE","place":"中東"},
	"TN":{"countryNameJP":"チュニジア","countryNameEN":"Tunisia","codeNum":"788","code3Char":"TUN","code2Char":"TN","place":"北アフリカ"},
	"TR":{"countryNameJP":"トルコ","countryNameEN":"Turkey","codeNum":"792","code3Char":"TUR","code2Char":"TR","place":"中東"},
	"TM":{"countryNameJP":"トルクメニスタン","countryNameEN":"Turkmenistan","codeNum":"795","code3Char":"TKM","code2Char":"TM","place":"中央アジア"},
	"TC":{"countryNameJP":"タークス・カイコス諸島","countryNameEN":"Turks and Caicos Islands","codeNum":"796","code3Char":"TCA","code2Char":"TC","place":"中央アメリカ"},
	"TV":{"countryNameJP":"ツバル","countryNameEN":"Tuvalu","codeNum":"798","code3Char":"TUV","code2Char":"TV","place":"オセアニア"},
	"UG":{"countryNameJP":"ウガンダ","countryNameEN":"Uganda","codeNum":"800","code3Char":"UGA","code2Char":"UG","place":"中央アフリカ"},
	"UA":{"countryNameJP":"ウクライナ","countryNameEN":"Ukraine","codeNum":"804","code3Char":"UKR","code2Char":"UA","place":"東ヨーロッパ"},
	"MK":{"countryNameJP":"マケドニア共和国","countryNameEN":"Macedonia, the former Yugoslav Republic of","codeNum":"807","code3Char":"MKD","code2Char":"MK","place":"東ヨーロッパ"},
	"EG":{"countryNameJP":"エジプト","countryNameEN":"Egypt","codeNum":"818","code3Char":"EGY","code2Char":"EG","place":"北アフリカ"},
	"GB":{"countryNameJP":"イギリス","countryNameEN":"United Kingdom","codeNum":"826","code3Char":"GBR","code2Char":"GB","place":"西ヨーロッパ"},
	"GG":{"countryNameJP":"ガーンジー","countryNameEN":"Guernsey","codeNum":"831","code3Char":"GGY","code2Char":"GG","place":"西ヨーロッパ"},
	"JE":{"countryNameJP":"ジャージー","countryNameEN":"Jersey","codeNum":"832","code3Char":"JEY","code2Char":"JE","place":"西ヨーロッパ"},
	"IM":{"countryNameJP":"マン島","countryNameEN":"Isle of Man","codeNum":"833","code3Char":"IMN","code2Char":"IM","place":"西ヨーロッパ"},
	"TZ":{"countryNameJP":"タンザニア","countryNameEN":"Tanzania, United Republic of","codeNum":"834","code3Char":"TZA","code2Char":"TZ","place":"東アフリカ"},
	"US":{"countryNameJP":"アメリカ合衆国","countryNameEN":"United States","codeNum":"840","code3Char":"USA","code2Char":"US","place":"北アメリカ"},
	"VI":{"countryNameJP":"アメリカ領ヴァージン諸島","countryNameEN":"Virgin Islands, U.S.","codeNum":"850","code3Char":"VIR","code2Char":"VI","place":"中央アメリカ"},
	"BF":{"countryNameJP":"ブルキナファソ","countryNameEN":"Burkina Faso","codeNum":"854","code3Char":"BFA","code2Char":"BF","place":"西アフリカ"},
	"UY":{"countryNameJP":"ウルグアイ","countryNameEN":"Uruguay","codeNum":"858","code3Char":"URY","code2Char":"UY","place":"南アメリカ"},
	"UZ":{"countryNameJP":"ウズベキスタン","countryNameEN":"Uzbekistan","codeNum":"860","code3Char":"UZB","code2Char":"UZ","place":"中央アジア"},
	"VE":{"countryNameJP":"ベネズエラ","countryNameEN":"Venezuela, Bolivarian Republic of","codeNum":"862","code3Char":"VEN","code2Char":"VE","place":"南アメリカ"},
	"WF":{"countryNameJP":"ウォリス・フツナ","countryNameEN":"Wallis and Futuna","codeNum":"876","code3Char":"WLF","code2Char":"WF","place":"オセアニア"},
	"WS":{"countryNameJP":"サモア","countryNameEN":"Samoa","codeNum":"882","code3Char":"WSM","code2Char":"WS","place":"オセアニア"},
	"YE":{"countryNameJP":"イエメン","countryNameEN":"Yemen","codeNum":"887","code3Char":"YEM","code2Char":"YE","place":"中東"},
	"ZM":{"countryNameJP":"ザンビア","countryNameEN":"Zambia","codeNum":"894","code3Char":"ZMB","code2Char":"ZM","place":"南アフリカ"}
};

